### PR TITLE
Additional chords

### PR DESCRIPTION
**Pull request by stufro**
I've added a few chords that I noticed were missing whilst integrating this with my project Chordly. See commit messages for what/why I've added.

Here's the diff of just what was added as it's harder to see on the PR diff due to the reorder.

```
diff --git a/lib/chord_diagrams/fingerings.csv b/lib/chord_diagrams/fingerings.csv
index 4fec7d5..52f4fa6 100644
--- a/lib/chord_diagrams/fingerings.csv
+++ b/lib/chord_diagrams/fingerings.csv
@@ -17,15 +17,26 @@ Am/G,302210,0000
 Am11,x00013,0055
 Am7,002010,0433
 Am9,x05557,1032
+Amaj7,x02120,1100
 Asus2,x02200,1341
 Asus4,x02230,2200
 B,x24442,4322
 B7,x21202,2322
+B7sus4,x22202,2422
 Bb,x13331,3211
+Bb7,x13131,1211
+Bbm,x13321,3111
+Bbm7,x13324,1111
 Bb/A,x00331,3210
+A#,x13331,3211
+A#7,x13131,1211
+A#m,x13321,3111
+A#m7,x13324,1111
+A#/A,x00331,3210
 Bm,x24432,3222
 Bm11,x20220,4200
 Bm7,x24232,2222
+Bsus4,x24452,4422
 C#,x46664,1114
 C#7,x46464,1112
 C#m,x46654,1104
@@ -37,10 +48,13 @@ C5,x355xx,0033
 C6,x32210,0000
 C7,x32310,0001
 C7/G,3323xx,0001
+C7sus4,x33310,0011
 CM7,x32000,0002
 Cadd9,x32033,0203
 Cm,x35543,0333
 Cm7,x35343,3333
+Cmaj7,x32000,0002
+Csus4,x33010,0013
 D#,x68886,0331
 D#5,x688xx,2255
 D#dim7,xx1212,2323
@@ -51,6 +65,7 @@ D5,x577xx,2200
 D6,xx0202,2222
 D7,x00212,2223
 D7/F#,200212,2223
+D7sus4,x00212,2233
 D9/F#,2x0210,5425
 DM7,xx0222,2224
 Dadd11,xx0032,0220
@@ -58,6 +73,7 @@ Daug,xx0332,3221
 Dm,x00231,2210
 Dm/F,10323x,2210
 Dm7,x00211,2213
+Dmaj7,xx0222,2224
 Dsus2,xx0230,2200
 Dsus4,xx0233,0230
 E,022100,4442
@@ -66,9 +82,19 @@ E7,020100,1202
 E7sus4,020200,2200
 EM7,xx2444,1302
 Eb,x68886,0331
+EbM7,x68786,0335
+Ebmaj7,x68786,0335
+Ebm,x68876,0321
+Ebm7,x68879,0324
+D#,x68886,0331
+D#M7,x68786,0335
+D#maj7,x68786,0335
+D#m,x68876,0321
+D#m7,x68879,0324
 Em,022000,0432
 Em7,020030,0202
 Em9/C,x34030,0605
+Emaj7,xx2444,1302
 Esus4,022200,4400
 F#,244322,3121
 F#7,242322,3424
@@ -78,10 +104,12 @@ F#m7,242222,2424
 F,133211,2010
 F/A,x03211,2010
 F7,131211,2313
+F7sus4,131311,3313
 FM7,132211,2413
 Fadd9,xx3213,0010
 Fm,133111,1013
 Fm7,131111,1313
+Fmaj7,132211,2413
 G#,466544,1343
 G#7,464544,1323
 G#dim,4564xx,1202
@@ -97,4 +125,6 @@ G7sus4,353533,0213
 GM7,320002,0222
 Gm,355333,0231
 Gm/Bb,x10333,0231
-Gm7,353333,0211
\ No newline at end of file
+Gm7,353333,0211
+Gmaj7,320002,0222
+Gsus4,320013,0233
\ No newline at end of file
```

### CODE REVIEW

**Comment by spilth** [comment]
@stufro Thank you for this.

I think in the future it would be good to separate out the alphabetizing from adding new chords in different PRs, but this is fine for now.

Was the `sheets` Rake task able to generate all of these and they look correct? It might be helpful to attach screenshots of those 🤔

**Comment by stufro** [comment]
Ah I wasn't aware of the sheets Rake task, nice :) I have run it now, I'm less experienced playing ukulele than guitar, but the new ones look ok to me.

# Guitar
Screenshot 2023-07-24 at 19 28 21


# Ukulele
Screenshot 2023-07-24 at 19 26 35

**Comment by spilth** [comment]
I'm gonna put aside some time to go through these and make sure they all sound right.

**Comment by spilth** [comment]
Hey @stufro. I went through all the guitar chords. The majority all look great. Just a few things I noticed:

- Do you think we should we have both M7 and maj7 entries? (We can merge without answering this immediately)
- A#m7/Bbm7 and D#m7/Ebm7 seem really hard to play. Are these actual chords and I just don't understand the finger of them?
- EM7 seems like it could include the E and A strings (I might be the source of this chord)

**Comment by stufro** [comment]
> Do you think we should we have both M7 and maj7 entries? (We can merge without answering this immediately)

I think it makes the library more flexible, different sources may have different preferences on how to spell a major 7 chord and this means it will work both ways.

> A#m7/Bbm7 and D#m7/Ebm7 seem really hard to play. Are these actual chords and I just don't understand the finger of them?

Yes I agree, I've updated those chords so you would play it by barring 1st fret for A, G and E strings.
Screenshot 2023-07-31 at 12 45 10
Screenshot 2023-07-31 at 12 45 21
Screenshot 2023-07-31 at 12 44 58
Screenshot 2023-07-31 at 12 45 03

> EM7 seems like it could include the E and A strings (I might be the source of this chord)

It could yes if you barred the A and D strings with your first finger.

**Comment by spilth** [comment]
@stufro I merged and pushed out version 0.0.15. Thanks for your contribution!

**Pull request merged**
